apiVersion: v1
kind: Pod
metadata:
  annotations: 
    goodbye-world: v1
  labels:
    app: goodbye-world
  name: goodbye-world
  namespace: goodbye-world
spec:
  imagePullSecrets:
  - name: aws-ecr-secret
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - hello-world
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: goodbye-world
    image: 379683964026.dkr.ecr.us-east-1.amazonaws.com/goodbye-world:v1.0.10
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000
      name: goodbye-world
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /api/v1/healthz
        port: 5000
        scheme: HTTP
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /api/v1/readiness
        port: 5000
        scheme: HTTP
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        memory: 170Mi
      requests:
        cpu: 100m
        memory: 70Mi
