HelloGoodbyeWorldOperator design:

- CRDs
  - installations.hellogoodbyeworld.io
    - helloGoodbyeWorldKubeControllerDeployment
  - status.hellogoodbyeworld.io

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    operator-language: python
  name: hellogoodbyeworldstatus.jonassteinberg.io
spec:
  conversion:
    strategy: None
  group: jonassteinberg.io
  names:
    kind: HelloGoodbyeWorldStatus
    listKind: HelloGoodbyeWorldStatusList
    plural: hellogoodbyeworldstatuses
    singular: hellogoodbyeworldstatus
    shortNames: hgb
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Whether the component running and stable.
      jsonPath: .status.conditions[?(@.type=='Available')].status
      name: Available
      type: string
    - description: Whether the component is processing changes.
      jsonPath: .status.conditions[?(@.type=='Progressing')].status
      name: Progressing
      type: string
    - description: Whether the component is degraded.
      jsonPath: .status.conditions[?(@.type=='Degraded')].status
      name: Degraded
      type: string
    - description: The time the component's Available status last changed.
      jsonPath: .status.conditions[?(@.type=='Available')].lastTransitionTime
      name: Since
      type: date
    name: v1
    schema:
      OpenAPIV3Schema:
        description: HelloGoodbyeWorldStatus represents the most recently observed status
          for a HelloWorldGoodbye
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: HelloGoodbyeWorldStatusSpec defines the desired state of HelloGoodbyeWorldStatus
            type: object
