apiVersion: v1
kind: Pod
metadata:
  annotations: 
    hello-world: v1
  labels:
    app: hello-world
  name: hello-world
  namespace: hello-world
spec:
  imagePullSecrets:
  - name: aws-ecr-secret
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - goodbye-world
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: hello-world
    image: 379683964026.dkr.ecr.us-east-1.amazonaws.com/hello-world:v1.0.5
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000
      name: hello-world
      protocol: TCP
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /api/v1/healthz
        port: 5000
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /api/v1/readiness
        port: 5000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 170Mi
      requests:
        cpu: 100m
        memory: 70Mi
