apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    hello-world: v1
  labels:
    app: hello-world
  name: hello-world
  namespace: hello-world
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - hello-world
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    spec:
      imagePullSecrets:
        - name: aws-ecr-secret
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - goodbye-world
                topologyKey: topology.kubernetes.io/zone
      containers:
        - name: hello-world
          image: 379683964026.dkr.ecr.us-east-1.amazonaws.com/hello-world:v1.0.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: hello-world
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/healthz
              port: 5000
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/readiness
              port: 5000
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              memory: 170Mi
            requests:
              cpu: 100m
              memory: 70Mi
