apiVersion: v1
kind: Service
metadata:
  annotations:
    hello-world: v1
  labels:
    app: hello-world
  name: hello-world
  namespace: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
